# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development
    env:
      CI: false
      VITE_ENV: ${{ vars.VITE_ENV }}
      VITE_TMA_LINK: ${{ vars.VITE_TMA_LINK }}
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v4
        with:
        # Version of pnpm to install
          version: latest # optional
        # Where to store pnpm files
        # dest: # optional, default is ~/setup-pnpm
        # If specified, run `pnpm install`
          run_install: true # optional, default is null

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
      - name: Upload Files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.DEPLOY_EC2_INSTANCE }}
          username: ec2-user
          key: ${{ secrets.SFTP_SSH_KEY }}
          port: 22
          source: "dist/"
          target: "/home/ec2-user/Sign-MiniApp"

